In [8]:
import sys
import os
import importlib

In [36]:
importlib.reload(data.loading)

In [15]:
src_dir = "../src/"
sys.path.append(src_dir)

In [37]:
from data.loading import json_to_df

In [38]:
df = json_to_df(verbose = True, save_to_csv = True)

2018-12-16 15:41:59,432 - data.loading - INFO - Creating DataFrame from jsons
2018-12-16 15:41:59,434 - data.loading - INFO - loading jsons from...
2018-12-16 15:41:59,435 - data.loading - INFO - 	jobs
2018-12-16 15:41:59,615 - data.loading - INFO - 	giphy
2018-12-16 15:41:59,623 - data.loading - INFO - 	doom
2018-12-16 15:42:01,706 - data.loading - INFO - 	vinyl
2018-12-16 15:42:01,991 - data.loading - INFO - 	rocket_comps
2018-12-16 15:42:01,996 - data.loading - INFO - 	notpython
2018-12-16 15:42:02,111 - data.loading - INFO - 	music_feeds
2018-12-16 15:42:06,350 - data.loading - INFO - 	amfest
2018-12-16 15:42:06,399 - data.loading - INFO - 	jazz-experimental
2018-12-16 15:42:06,473 - data.loading - INFO - 	gamedev
2018-12-16 15:42:06,525 - data.loading - INFO - 	notdoom
2018-12-16 15:42:07,412 - data.loading - INFO - 	日本語
2018-12-16 15:42:07,451 - data.loading - INFO - 	techno
2018-12-16 15:42:07,481 - data.loading - INFO - 	random
2018-12-16 15:42:09,007 - data.loading - INFO - 	scala
2018-12-16 15:42:09,024 - data.loading - INFO - 	temples
2018-12-16 15:42:09,240 - data.loading - INFO - 	beer
2018-12-16 15:42:09,287 - data.loading - INFO - 	instagram
2018-12-16 15:42:09,377 - data.loading - INFO - 	doomlist
2018-12-16 15:42:09,392 - data.loading - INFO - 	bandnames
2018-12-16 15:42:09,445 - data.loading - INFO - 	webdev
2018-12-16 15:42:09,657 - data.loading - INFO - 	articles
2018-12-16 15:42:10,172 - data.loading - INFO - 	extrememetal
2018-12-16 15:42:10,730 - data.loading - INFO - 	health
2018-12-16 15:42:10,885 - data.loading - INFO - 	tv
2018-12-16 15:42:13,937 - data.loading - INFO - 	wrestling
2018-12-16 15:42:13,994 - data.loading - INFO - 	chat
2018-12-16 15:42:17,600 - data.loading - INFO - 	zugzug
2018-12-16 15:42:18,778 - data.loading - INFO - 	fuzzclub
2018-12-16 15:42:18,787 - data.loading - INFO - 	roadburn
2018-12-16 15:42:20,052 - data.loading - INFO - 	promotion
2018-12-16 15:42:20,903 - data.loading - INFO - 	clan-doomsters
2018-12-16 15:42:21,023 - data.loading - INFO - 	gifs
2018-12-16 15:42:21,309 - data.loading - INFO - 	food
2018-12-16 15:42:21,440 - data.loading - INFO - 	announcements
2018-12-16 15:42:24,414 - data.loading - INFO - 	desertfest
2018-12-16 15:42:24,421 - data.loading - INFO - 	boardandcard
2018-12-16 15:42:24,954 - data.loading - INFO - 	rp
2018-12-16 15:42:25,006 - data.loading - INFO - 	telegram
2018-12-16 15:42:25,023 - data.loading - INFO - 	games
2018-12-16 15:42:26,036 - data.loading - INFO - 	atp
2018-12-16 15:42:26,108 - data.loading - INFO - 	techart
2018-12-16 15:42:26,312 - data.loading - INFO - 	literature
2018-12-16 15:42:26,339 - data.loading - INFO - 	carcru
2018-12-16 15:42:26,482 - data.loading - INFO - 	tech
2018-12-16 15:42:27,892 - data.loading - INFO - 	foreign
2018-12-16 15:42:27,938 - data.loading - INFO - 	dreams
2018-12-16 15:42:27,960 - data.loading - INFO - 	crypto
2018-12-16 15:42:28,000 - data.loading - INFO - 	dub
2018-12-16 15:42:28,094 - data.loading - INFO - 	pokeymanz
2018-12-16 15:42:28,122 - data.loading - INFO - 	hespsspammylinkroom
2018-12-16 15:42:28,127 - data.loading - INFO - 	vr
2018-12-16 15:42:28,138 - data.loading - INFO - 	bristol
2018-12-16 15:42:31,109 - data.loading - INFO - 	soundcloud
2018-12-16 15:42:31,113 - data.loading - INFO - 	film
2018-12-16 15:42:31,289 - data.loading - INFO - 	onmyway
2018-12-16 15:42:31,452 - data.loading - INFO - 	lastfm
2018-12-16 15:42:31,470 - data.loading - INFO - 	notts
2018-12-16 15:42:33,321 - data.loading - INFO - 	guff
2018-12-16 15:42:36,603 - data.loading - INFO - 	albumlistdev
2018-12-16 15:42:36,682 - data.loading - INFO - 	dunajam
2018-12-16 15:42:36,704 - data.loading - INFO - 	comix
2018-12-16 15:42:36,842 - data.loading - INFO - 	spotify
2018-12-16 15:42:36,875 - data.loading - INFO - 	bragging
2018-12-16 15:42:37,590 - data.loading - INFO - 	writing
2018-12-16 15:42:37,625 - data.loading - INFO - 	psychedelic
2018-12-16 15:42:38,534 - data.loading - INFO - 	debate
2018-12-16 15:42:38,567 - data.loading - INFO - 	festivals
2018-12-16 15:42:39,965 - data.loading - INFO - 	sublime
2018-12-16 15:42:39,979 - data.loading - INFO - 	watchthis
2018-12-16 15:42:40,388 - data.loading - INFO - 	nanogenmo
2018-12-16 15:42:40,397 - data.loading - INFO - 	hearthstone
2018-12-16 15:42:40,456 - data.loading - INFO - 	androidcats
2018-12-16 15:42:40,482 - data.loading - INFO - 	sql
2018-12-16 15:42:40,650 - data.loading - INFO - 	bandcamp
2018-12-16 15:42:40,654 - data.loading - INFO - 	postrock
2018-12-16 15:42:41,015 - data.loading - INFO - 	munney
2018-12-16 15:42:41,033 - data.loading - INFO - 	politics
2018-12-16 15:42:42,084 - data.loading - INFO - 	ark
2018-12-16 15:42:42,093 - data.loading - INFO - 	reviews
2018-12-16 15:42:42,109 - data.loading - INFO - 	fileshare
2018-12-16 15:42:42,293 - data.loading - INFO - 	arctangent
2018-12-16 15:42:42,402 - data.loading - INFO - 	pipegigging
2018-12-16 15:42:42,438 - data.loading - INFO - 	python
2018-12-16 15:42:43,833 - data.loading - INFO - concatenating data to single DataFrame
2018-12-16 15:42:44,244 - data.loading - INFO - saving to ../data/interim/slack_data.csv

In [32]:
df.head()

,attachments,bot_id,bot_link,channel,client_msg_id,display_as_bot,edited,files,icons,inviter,...,root,subtype,text,thread_ts,topic,ts,type,upload,user,username
0,[{'title': 'Explosive Research Scientist - Civ...,NaN,NaN,jobs,19528caa-200a-4c5c-a6f8-3a828d5aca85,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,<https://www.civilservicejobs.service.gov.uk/c...,NaN,NaN,1.539165e+09,message,NaN,U0A2M655L,NaN
1,NaN,NaN,NaN,jobs,aa156292-1d78-48da-bc2c-1b77af8b72e5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,I just like the job title,NaN,NaN,1.539165e+09,message,NaN,U0A2M655L,NaN
0,NaN,NaN,NaN,jobs,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Headfirst Bristol are looking for an iOS (Swif...,NaN,NaN,1.493127e+09,message,NaN,U0A1YF4MR,NaN
1,NaN,NaN,NaN,jobs,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,slackbot_response,"BURRRRSTAAALLLLL, Bristol \o/, Bristol!!??!?!",NaN,NaN,1.493127e+09,message,NaN,USLACKBOT,NaN
0,"[{'service_name': 'Potato', 'title': 'Jobs', '...",NaN,NaN,jobs,d834ffa6-c6d3-4334-936b-916cba6e7ff2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,lots of <#C1CU6L33N|jobs> at Potato again: <ht...,NaN,NaN,1.533893e+09,message,NaN,U0A1YF4MR,NaN

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 105812 entries, 0 to 14
Data columns (total 32 columns):
attachments          24524 non-null object
bot_id               19922 non-null object
bot_link             13 non-null object
channel              105812 non-null object
client_msg_id        9852 non-null object
display_as_bot       360 non-null object
edited               2178 non-null object
files                360 non-null object
icons                7647 non-null object
inviter              359 non-null object
item_type            39 non-null object
latest_reply         261 non-null float64
name                 6 non-null object
new_broadcast        2 non-null float64
old_name             6 non-null object
parent_user_id       1418 non-null object
purpose              48 non-null object
reactions            1284 non-null object
replies              261 non-null object
reply_count          261 non-null float64
reply_users          261 non-null object
reply_users_count    261 non-null float64
root                 29 non-null object
subtype              22220 non-null object
text                 105812 non-null object
thread_ts            1762 non-null float64
topic                36 non-null object
ts                   105812 non-null float64
type                 105812 non-null object
upload               360 non-null object
user                 86033 non-null object
username             9875 non-null object
dtypes: float64(6), object(26)
memory usage: 26.6+ MB

In [34]:
df.describe()

,latest_reply,new_broadcast,reply_count,reply_users_count,thread_ts,ts
count,2.610000e+02,2.0,261.000000,261.000000,1.762000e+03,1.058120e+05
mean,1.502173e+09,1.0,5.750958,1.743295,1.525521e+09,1.485959e+09
std,1.631776e+08,0.0,17.838033,0.798558,1.712433e+07,2.922128e+07
min,0.000000e+00,1.0,0.000000,0.000000,1.484871e+09,1.441203e+09
25%,1.507077e+09,1.0,1.000000,1.000000,1.512988e+09,1.460581e+09
50%,1.521586e+09,1.0,2.000000,2.000000,1.532470e+09,1.481140e+09
75%,1.534702e+09,1.0,5.000000,2.000000,1.541677e+09,1.511278e+09
max,1.543242e+09,1.0,267.000000,5.000000,1.543237e+09,1.543528e+09